DROP TABLE SPRING_DEV.M_USER PURGE;

CREATE TABLE SPRING_DEV.M_USER (
    USER_ID NUMBER(19,0) PRIMARY KEY,
    USER_CODE CHAR(8) NOT NULL,
    PASSWORD VARCHAR(16) NOT NULL,
    USER_NAME VARCHAR(100),
    MAIL_ADDRESS VARCHAR(100),
    ENTRY_DATE TIMESTAMP,
    ENTRY_USER CHAR(8),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER CHAR(8),
    DELETE_FLG NUMERIC(1)
    );

 CREATE SEQUENCE SPRING_DEV.USER_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE;