DROP TABLE SPRING_DEV.T_BALANCE_OF_PAYMENTS PURGE;

CREATE TABLE SPRING_DEV.T_BALANCE_OF_PAYMENTS (
    BALANCE_OF_PAYMENTS_ID NUMBER(19,0) PRIMARY KEY,
    ACCOUNT_ID NUMBER(19,0) NOT NULL,
    BALANCE_OF_PAYMENTS_KUBUN CHAR(1),
    BALANCE_OF_PAYMENTS_SIGN NUMBER(19,0),
    EXPENSES_KUBUN CHAR(2),
    AMOUNT NUMBER(19,0),
    TRANSACTION_DATE DATE,
    ENTRY_DATE TIMESTAMP,
    ENTRY_USER CHAR(8),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER CHAR(8),
    DELETE_FLG NUMERIC(1)
    );

 CREATE SEQUENCE SPRING_DEV.BALANCE_OF_PAYMENTS_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE;