DROP TABLE SPRING_DEV.M_ACCOUNT PURGE;

CREATE TABLE SPRING_DEV.M_ACCOUNT (
    ACCOUNT_ID NUMBER(19,0) PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(30),
    ACCOUNT_NUMBER CHAR(16) NOT NULL,
    USER_ID NUMBER(19,0) NOT NULL,
    ACCOUNT_KUBUN CHAR(1),
    ENTRY_DATE TIMESTAMP,
    ENTRY_USER CHAR(8),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER CHAR(8),
    DELETE_FLG NUMERIC(1)
    );

 CREATE SEQUENCE SPRING_DEV.ACCOUNT_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE;