CREATE TABLE M_USER (
    USER_ID NUMBER(19,0) NOT NULL,
    USER_CODE CHAR(8) NOT NULL,
    PASSWORD VARCHAR(16) NOT NULL,
    USER_NAME VARCHAR(20),
    MAIL_ADDRESS VARCHAR(100),
    ENTRY_DATE DATE,
    ENTRY_USER CHAR(8),
    DELETE_FLG NUMERIC(1)
    );

 CREATE SEQUENCE USER_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE;