DROP TABLE SPRING_DEV.T_BALANCE PURGE;

CREATE TABLE SPRING_DEV.T_BALANCE (
    ACCOUNT_ID NUMBER(19,0) PRIMARY KEY,
    BALANCE NUMBER(19,0),
    LATEST_BALANCE_HISTORY_ID NUMBER(19,0),
    ENTRY_DATE TIMESTAMP,
    ENTRY_USER CHAR(8),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER CHAR(8),
    DELETE_FLG NUMERIC(1)
    );
