DROP TABLE SPRING_DEV.T_BALANCE_HISTORY PURGE;

CREATE TABLE SPRING_DEV.T_BALANCE_HISTORY (
    BALANCE_HISTORY_ID NUMBER(19,0) PRIMARY KEY,
    ACCOUNT_ID NUMBER(19,0) NOT NULL,
    BALANCE NUMBER(19,0),
    LATEST_BALANCE_HISTORY_ID NUMBER(19,0),
    EARNINGS_AND_EXPENSES_ID NUMBER(19,0),
    ENTRY_DATE TIMESTAMP,
    ENTRY_USER CHAR(8),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER CHAR(8),
    DELETE_FLG NUMERIC(1)
    );

 CREATE SEQUENCE SPRING_DEV.BALANCE_HISTORY_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE;