DROP TABLE SPRING_DEV.T_EARNINGS_AND_EXPENSES PURGE;

CREATE TABLE SPRING_DEV.T_EARNINGS_AND_EXPENSES (
    EARNINGS_AND_EXPENSES_ID NUMBER(19,0) PRIMARY KEY,
    ACCOUNT_ID NUMBER(19,0) NOT NULL,
    EARNINGS_AND_EXPENSES_KUBUN CHAR(1),
    AMOUNT NUMBER(19,0),
    TRANSACTION_DATE DATE,
    ENTRY_DATE TIMESTAMP,
    ENTRY_USER CHAR(8),
    UPDATE_DATE TIMESTAMP,
    UPDATE_USER CHAR(8),
    DELETE_FLG NUMERIC(1)
    );

 CREATE SEQUENCE SPRING_DEV.EARNINGS_AND_EXPENSES_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99999
    NOCYCLE
    NOCACHE;